version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: notifyx_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-notifyx_db}
      POSTGRES_USER: ${POSTGRES_USER:-notifyx_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-notifyx_secret_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notifyx_user -d notifyx_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: notifyx_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notifyx_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://notifyx_user:notifyx_secret_password@db:5432/notifyx_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=django-insecure-notifyx-enterprise-platform-key-production-ready
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notifyx_worker
    command: celery -A config worker --loglevel=info -c 4 -Q default,high_priority,bulk
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://notifyx_user:notifyx_secret_password@db:5432/notifyx_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notifyx_beat
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://notifyx_user:notifyx_secret_password@db:5432/notifyx_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
